name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Stop container
      run: docker stop psychological-help-container-be || true
    - name: Delete old container
      run: docker rm -f psychological-help-container-be || true
    - name: Delete old image
      run: docker image rm danylotrofymov/psychological-help-be || true
    - name: Pull docker image
      run: docker pull danylotrofymov/psychological-help-be:latest
    - name: Run new container
      run: docker run -d -p 3001:3001 --network psycho-help --name psychological-help-container-be danylotrofymov/psychological-help-be 
