name: CI

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create google cloud file
    - run: cat <<EOF > .google-env.json
          "$GOOGLE_ENV"
          EOF
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build docker image
      run: docker build --tag danylotrofymov/psychological-help-be . --build-arg DATABASE_URL=${{secrets.DATABASE_URL}} --build-arg JWT_SECRET=${{secrets.JWT_SECRET}} --build-arg TELEGRAM_BOT_TOKEN=${{secrets.TELEGRAM_BOT_TOKEN}} --build-arg GOOGLE_PROJECT_ID=${{secrets.GOOGLE_PROJECT_ID}}
    - name: Push to Dockerhub
      run: docker push danylotrofymov/psychological-help-be:latest
